<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Problem-Statement:" data-toc-modified-id="Problem-Statement:-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Problem Statement:</a></span><ul class="toc-item"><li><span><a href="#Dataset-Description:" data-toc-modified-id="Dataset-Description:-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Dataset Description:</a></span></li><li><span><a href="#Atribute-description" data-toc-modified-id="Atribute-description-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Atribute description</a></span></li></ul></li><li><span><a href="#Import-libraries" data-toc-modified-id="Import-libraries-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import libraries</a></span></li><li><span><a href="#Load-data" data-toc-modified-id="Load-data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Load data</a></span></li><li><span><a href="#Data-Understanding" data-toc-modified-id="Data-Understanding-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Data Understanding</a></span><ul class="toc-item"><li><span><a href="#Number-of-records-and-columns" data-toc-modified-id="Number-of-records-and-columns-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Number of records and columns</a></span></li><li><span><a href="#See-the-first-five-records" data-toc-modified-id="See-the-first-five-records-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>See the first five records</a></span></li><li><span><a href="#Different-classes-in-Outcome-variable" data-toc-modified-id="Different-classes-in-Outcome-variable-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Different classes in Outcome variable</a></span></li><li><span><a href="#Display-data-type-of-each-variable" data-toc-modified-id="Display-data-type-of-each-variable-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Display data type of each variable</a></span></li><li><span><a href="#Identifying-categorical-attributes" data-toc-modified-id="Identifying-categorical-attributes-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Identifying categorical attributes</a></span></li><li><span><a href="#Converting-to-appropriate-datatype" data-toc-modified-id="Converting-to-appropriate-datatype-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Converting to appropriate datatype</a></span></li><li><span><a href="#Display-data-type-of-each-variable-after-conversion" data-toc-modified-id="Display-data-type-of-each-variable-after-conversion-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Display data type of each variable after conversion</a></span></li><li><span><a href="#Dropping-ID-column-and-checking-the-length-of-columns" data-toc-modified-id="Dropping-ID-column-and-checking-the-length-of-columns-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>Dropping ID column and checking the length of columns</a></span></li><li><span><a href="#Display-summary-statistics" data-toc-modified-id="Display-summary-statistics-4.9"><span class="toc-item-num">4.9&nbsp;&nbsp;</span>Display summary statistics</a></span></li><li><span><a href="#Check-the-distribution-of-all-categorical-attributes" data-toc-modified-id="Check-the-distribution-of-all-categorical-attributes-4.10"><span class="toc-item-num">4.10&nbsp;&nbsp;</span>Check the distribution of all categorical attributes</a></span></li><li><span><a href="#Checking-for-null-values" data-toc-modified-id="Checking-for-null-values-4.11"><span class="toc-item-num">4.11&nbsp;&nbsp;</span>Checking for null values</a></span></li></ul></li><li><span><a href="#Divide-the-data-into-train-and-test" data-toc-modified-id="Divide-the-data-into-train-and-test-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Divide the data into train and test</a></span></li><li><span><a href="#Preprocessing" data-toc-modified-id="Preprocessing-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Preprocessing</a></span><ul class="toc-item"><li><span><a href="#Display-all-the-columns" data-toc-modified-id="Display-all-the-columns-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Display all the columns</a></span></li><li><span><a href="#Creating-a-list-of-numerical-attributes-and-categorical-list" data-toc-modified-id="Creating-a-list-of-numerical-attributes-and-categorical-list-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Creating a list of numerical attributes and categorical list</a></span></li><li><span><a href="#LabelEncoder--:-Target-Attributes" data-toc-modified-id="LabelEncoder--:-Target-Attributes-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>LabelEncoder  : Target Attributes</a></span></li><li><span><a href="#Standard-Scaler-:-Independent-Numberic-Attributes" data-toc-modified-id="Standard-Scaler-:-Independent-Numberic-Attributes-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Standard Scaler : Independent Numberic Attributes</a></span></li><li><span><a href="#OneHotEncoder-:-Independent-Categorical-Attributes" data-toc-modified-id="OneHotEncoder-:-Independent-Categorical-Attributes-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>OneHotEncoder : Independent Categorical Attributes</a></span></li><li><span><a href="#Concatenate" data-toc-modified-id="Concatenate-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Concatenate</a></span></li></ul></li><li><span><a href="#Error-Metrics" data-toc-modified-id="Error-Metrics-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Error Metrics</a></span><ul class="toc-item"><li><span><a href="#Function-to-calculate-accuracy,-recall,-precision-and-F1-score" data-toc-modified-id="Function-to-calculate-accuracy,-recall,-precision-and-F1-score-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Function to calculate accuracy, recall, precision and F1 score</a></span></li><li><span><a href="#Function-for-Classification-Report" data-toc-modified-id="Function-for-Classification-Report-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Function for Classification Report</a></span></li></ul></li><li><span><a href="#Model-Building" data-toc-modified-id="Model-Building-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Model Building</a></span><ul class="toc-item"><li><span><a href="#Decision-Trees" data-toc-modified-id="Decision-Trees-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Decision Trees</a></span></li><li><span><a href="#Random-Forests" data-toc-modified-id="Random-Forests-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Random Forests</a></span></li><li><span><a href="#AdaBoost" data-toc-modified-id="AdaBoost-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>AdaBoost</a></span></li><li><span><a href="#Build-Gradient-Boosting-Classifier" data-toc-modified-id="Build-Gradient-Boosting-Classifier-8.4"><span class="toc-item-num">8.4&nbsp;&nbsp;</span>Build Gradient Boosting Classifier</a></span><ul class="toc-item"><li><span><a href="#XGBOOST" data-toc-modified-id="XGBOOST-8.4.1"><span class="toc-item-num">8.4.1&nbsp;&nbsp;</span>XGBOOST</a></span><ul class="toc-item"><li><span><a href="#Create-XGBoost-Classifier" data-toc-modified-id="Create-XGBoost-Classifier-8.4.1.1"><span class="toc-item-num">8.4.1.1&nbsp;&nbsp;</span>Create XGBoost Classifier</a></span></li></ul></li><li><span><a href="#Extracting-the-important-features" data-toc-modified-id="Extracting-the-important-features-8.4.2"><span class="toc-item-num">8.4.2&nbsp;&nbsp;</span>Extracting the important features</a></span></li></ul></li><li><span><a href="#Stacking:" data-toc-modified-id="Stacking:-8.5"><span class="toc-item-num">8.5&nbsp;&nbsp;</span>Stacking:</a></span><ul class="toc-item"><li><span><a href="#References:" data-toc-modified-id="References:-8.5.1"><span class="toc-item-num">8.5.1&nbsp;&nbsp;</span>References:</a></span></li></ul></li></ul></li></ul></div>

# Problem Statement: 

Tennis Australia Open is trying to better automate how tennis points get categorized into three outcomes – 

* `Winner` – the point winning player hits a shot that is not touched by the opponent
* `Forced error` – the point winning player hits a shot that causes the opponent to not be able to return it, i.e. a good shot that is hard to handle
* `Unforced error` – the player attempting to return the ball makes an error on an otherwise normal looking rally shot

## Dataset Description:

The dataset includes point outcomes of rallies only (where the number of shots hit exceeds two, which represents the serve and return). All points were played at a past Australian Open.

## Atribute description

| Variable | Description| Value Range |
| :- | -: | :-: |
rally | The number of shots in the point counting serves and point-ending shot | An integer from 1, 2, 3...
| serve | A number indicating whether the point was played on a first or second serve.  | 1 = First, 2 = Second
| hitpoint | Shot category for point-ending shot | F = Forehand, B = Backhand, V = Volley, U = Unknown
| speed | Speed of point-ending shot | Continuous (m/s)
| net.clearance | Distance above the net as point-ending shot passed the net | Continuous (cm) distance above net. Can be negative if shot did not pass above the net.
| distance.from.sideline | Lateral distance of the point-ending shot bounce from the nearest singles sideline. | Perpendicular distance in meters (always positive even if out)
| depth | Distance of the point-ending shot bounce from the baseline | Perpendicular distance in meters
(always positive even if out)
| outside.sideline | Logical indicator of whether point-ending shot landed outside of the in-play singles sideline | TRUE, FALSE
| outside.baseline | Logical indicator of whether point-ending shot landed beyond the in-play baseline | TRUE, FALSE
| player.distance.travelled | Distance player who made the point-ending shot travelled between the impact of the penultimate shot and the impact of the point-ending shot | Euclidean distance in meters
| player.impact.depth | Distance of player who made point-ending shot from the net at the time the point-ending shot was made | Perpendicular distance along the length of court from net in meters
| player.impact.distance.from.center | Distance of player who made point-ending shot from the center line at the time the point-ending shot was made | Perpendicular distance from the center line in meters
| player.depth | Distance of player who made point-ending shot from the net at the time the penultimate shot was made | Perpendicular distance along the length of court from net in meters
| player.distance.from.center | Distance of player who made point-ending shot from the center line at the time the penultimate shot was made | Perpendicular distance from the center line in meters
| opponent.depth | Distance of opponent from the net at the time the at the time the penultimate shot was made | Perpendicular distance along the length of court from net in meters
| opponent.distance.from.center | Distance of opponent from the center line at the time the penultimate shot was made | Perpendicular distance from the center line in meters
| same.side | Logical indicator if both player and opponent were positioned on the same side of the center line (ad or deuce court) at the time the penultimate shot was made | TRUE, FALSE
| previous.speed | Speed of penultimate shot | Continuous (m/s)
| previous.net.clearance | Distance above the net as penultimate shot passed the net | Continuous (cm) distance above net. Can be negative if shot did not pass above the net.
| previous.distance.from.sideline | Lateral distance of the penultimate  shot bounce from the nearest singles sideline. | Perpendicular distance in meters (always positive even if out)
| previous.depth | Distance of the penultimate shot bounce from the baseline | Perpendicular distance in meters
(always positive even if out)
| previous.hitpoint | Shot category for penultimate shot | F = Forehand, B = Backhand, V = Volley, U = Unknown
| previous.time.to.net | Time for penultimate shot to be hit and pass the net | Continuous number in seconds
| server.is.impact.player | Logical if player who made point-ending shot was the server of the point | TRUE, FALSE
| outcome | Target variable, character with three categories indicating the type of shot that ended the point  | W (Winner), FE (Forced Error), UE (Unforced Error)
| id | A 10-character unique identifier for the point | Character

# Import libraries

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier

#from xgboost import XGBClassifier

#from vecstack import stacking

from sklearn.model_selection import GridSearchCV

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder


# Load data

In [4]:
#Load Data
df=pd.read_csv("tennis.csv")
#Read column name
#describe



In [5]:
df.columns

Index(['rally', 'serve', 'hitpoint', 'speed', 'net.clearance',
       'distance.from.sideline', 'depth', 'outside.sideline',
       'outside.baseline', 'player.distance.travelled', 'player.impact.depth',
       'player.impact.distance.from.center', 'player.depth',
       'player.distance.from.center', 'previous.speed',
       'previous.net.clearance', 'previous.distance.from.sideline',
       'previous.depth', 'opponent.depth', 'opponent.distance.from.center',
       'same.side', 'previous.hitpoint', 'previous.time.to.net',
       'server.is.impact.player', 'outcome', 'gender', 'ID'],
      dtype='object')

In [6]:
#df.describe

In [7]:
#np.dtype(df).sum()

In [8]:
#Find any nulls???
df.isnull().sum()

rally                                 0
serve                                 0
hitpoint                              0
speed                                 0
net.clearance                         0
distance.from.sideline                0
depth                                 0
outside.sideline                      0
outside.baseline                      0
player.distance.travelled             0
player.impact.depth                   0
player.impact.distance.from.center    0
player.depth                          0
player.distance.from.center           0
previous.speed                        0
previous.net.clearance                0
previous.distance.from.sideline       0
previous.depth                        0
opponent.depth                        0
opponent.distance.from.center         0
same.side                             0
previous.hitpoint                     0
previous.time.to.net                  0
server.is.impact.player               0
outcome                               0


In [9]:
df.dtypes

rally                                   int64
serve                                   int64
hitpoint                               object
speed                                 float64
net.clearance                         float64
distance.from.sideline                float64
depth                                 float64
outside.sideline                         bool
outside.baseline                         bool
player.distance.travelled             float64
player.impact.depth                   float64
player.impact.distance.from.center    float64
player.depth                          float64
player.distance.from.center           float64
previous.speed                        float64
previous.net.clearance                float64
previous.distance.from.sideline       float64
previous.depth                        float64
opponent.depth                        float64
opponent.distance.from.center         float64
same.side                                bool
previous.hitpoint                 

# Data Understanding

In [10]:
# drop unnecessry cols
df.drop(['gender', 'ID'],axis=1, inplace=True)

In [11]:
#Copy output into y and remaining columns into X
y=df['outcome']
X=df.drop(['outcome'],axis=1)

In [12]:
df.nunique()

rally                                   30
serve                                    2
hitpoint                                 4
speed                                 8001
net.clearance                         7994
distance.from.sideline                8001
depth                                 8001
outside.sideline                         2
outside.baseline                         2
player.distance.travelled             7988
player.impact.depth                   7089
player.impact.distance.from.center    6644
player.depth                          6882
player.distance.from.center           5977
previous.speed                        8001
previous.net.clearance                8001
previous.distance.from.sideline       8001
previous.depth                        8001
opponent.depth                        6856
opponent.distance.from.center         6775
same.side                                2
previous.hitpoint                        4
previous.time.to.net                  8001
server.is.i

In [13]:
df.columns

Index(['rally', 'serve', 'hitpoint', 'speed', 'net.clearance',
       'distance.from.sideline', 'depth', 'outside.sideline',
       'outside.baseline', 'player.distance.travelled', 'player.impact.depth',
       'player.impact.distance.from.center', 'player.depth',
       'player.distance.from.center', 'previous.speed',
       'previous.net.clearance', 'previous.distance.from.sideline',
       'previous.depth', 'opponent.depth', 'opponent.distance.from.center',
       'same.side', 'previous.hitpoint', 'previous.time.to.net',
       'server.is.impact.player', 'outcome'],
      dtype='object')

In [14]:
#copy the numerical columns labels into num_cols, 
#copy the Object columns labels into cat_cols, 
#num_cols = X.select_dtypes(include=['int64','float64'])
cat_cols = ['serve', 'hitpoint','outside.sideline','outside.baseline','same.side', 'previous.hitpoint',
            'server.is.impact.player']

In [15]:
num_cols= df.drop(cat_cols, axis=1)

In [17]:
num_cols.drop('outcome' ,axis=1, inplace=True)

In [18]:
num_cols=num_cols.columns

In [20]:
df.rally.unique()

array([ 4, 23,  9, 10,  7,  3, 11, 20, 19,  6,  5, 12, 16,  8, 25, 15, 14,
       21, 22, 13, 17, 18, 30, 28, 26, 32, 38, 24, 27, 29], dtype=int64)

In [21]:
df.serve.unique()

array([1, 2], dtype=int64)

In [62]:
#Convert cat_cols into type category  using astype
X[cat_cols] = X[cat_cols].astype('object')

In [63]:
#convert outcome also into category
df['outcome']=df['outcome'].astype('category')

In [64]:
#copy it into y
y = df['outcome'] 

In [65]:
# split the data
X_train, X_test, y_train, y_test =  train_test_split(X,y,test_size=0.3,random_state=0)

In [66]:
df[['hitpoint', 'outside.sideline', 'outside.baseline', 'same.side',
       'previous.hitpoint', 'server.is.impact.player']].nunique()

hitpoint                   4
outside.sideline           2
outside.baseline           2
same.side                  2
previous.hitpoint          4
server.is.impact.player    2
dtype: int64

In [67]:
new_df=X[['hitpoint','previous.hitpoint']]

In [68]:
X.dtypes

rally                                   int64
serve                                  object
hitpoint                               object
speed                                 float64
net.clearance                         float64
distance.from.sideline                float64
depth                                 float64
outside.sideline                       object
outside.baseline                       object
player.distance.travelled             float64
player.impact.depth                   float64
player.impact.distance.from.center    float64
player.depth                          float64
player.distance.from.center           float64
previous.speed                        float64
previous.net.clearance                float64
previous.distance.from.sideline       float64
previous.depth                        float64
opponent.depth                        float64
opponent.distance.from.center         float64
same.side                              object
previous.hitpoint                 

In [69]:
df.hitpoint.value_counts()

F    4402
B    3034
U     429
V     136
Name: hitpoint, dtype: int64

In [70]:
df['outside.sideline'].unique()

array([False,  True])

In [71]:
df['outside.baseline'].unique()

array([False,  True])

In [72]:
df['same.side'].unique()

array([ True, False])

In [73]:
df['server.is.impact.player'].unique()

array([False,  True])

In [74]:
df['previous.hitpoint'].value_counts()

F    3684
B    3278
V     720
U     319
Name: previous.hitpoint, dtype: int64

In [75]:
y_train

5280     W
6032     W
1732    UE
5267    FE
2161    UE
        ..
4931    FE
3264    UE
1653    FE
2607    FE
2732     W
Name: outcome, Length: 5600, dtype: category
Categories (3, object): ['FE', 'UE', 'W']

In [76]:
# transform y using label encoder, fit, transform
le = LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [77]:
#Create a pipeline
#Numneric transformer, what are the opearations that we perform on 
#1. Missing data, 2. Standardization

numeric_transformer = Pipeline(steps=[('missing_value',SimpleImputer(strategy='mean')),
                     ('scalar1',StandardScaler())])



In [78]:
categorical_transformer = Pipeline(steps=[('missing_value1',SimpleImputer(missing_values=np.nan,strategy='most_frequent')),
                                     ('onehotencode',OneHotEncoder() )])

In [79]:
#Create a pipeline
#categorical_transformer , what are the opearations that we perform on 
#1. Missing data, 2. onehot encoder

#categorical_transformer 

In [80]:
num_cols_names

Index(['rally', 'serve', 'speed', 'net.clearance', 'distance.from.sideline',
       'depth', 'player.distance.travelled', 'player.impact.depth',
       'player.impact.distance.from.center', 'player.depth',
       'player.distance.from.center', 'previous.speed',
       'previous.net.clearance', 'previous.distance.from.sideline',
       'previous.depth', 'opponent.depth', 'opponent.distance.from.center',
       'previous.time.to.net'],
      dtype='object')

In [81]:
#ColumnTransformer

preprocessor=ColumnTransformer(transformers=[('num',numeric_transformer, num_cols_names),('cat',categorical_transformer,cat_cols_names)])

In [82]:
#Pipeline preprocessor, clssifier

RF_pipe = Pipeline(steps=[('pp',preprocessor),
                   ('det_classifier', DecisionTreeClassifier())])


In [83]:
RF_pipe.fit(X_train, y_train)

Pipeline(steps=[('pp',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('missing_value',
                                                                   SimpleImputer()),
                                                                  ('scalar1',
                                                                   StandardScaler())]),
                                                  Index(['rally', 'serve', 'speed', 'net.clearance', 'distance.from.sideline',
       'depth', 'player.distance.travelled', 'player.impact.depth',
       'player.impact.distance.from.center', 'player.depth',
       'player.distance.from.cent...
       'previous.depth', 'opponent.depth', 'opponent.distance.from.center',
       'previous.time.to.net'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('missing_value1',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencode',
                                                                   OneHotEncoder())]),
                                                  Index(['hitpoint', 'outside.sideline', 'outside.baseline', 'same.side',
       'previous.hitpoint', 'server.is.impact.player'],
      dtype='object'))])),
                ('det_classifier', DecisionTreeClassifier())])

In [84]:
#Write a function to display all the metrics

#Accuracy, confusion matrix, recall, precision etc 
def evaluate_model(act, pred):

SyntaxError: unexpected EOF while parsing (<ipython-input-84-814deb224636>, line 4)

In [40]:
ohe=OneHotEncoder()

In [42]:
enc_data=pd.DataFrame(ohe.fit_transform(new_df).toarray())

In [43]:
enc_data

0    1    2    3    4    5    6    7
0     1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
1     1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
2     1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
3     0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
4     1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...
7996  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
7997  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
7998  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
7999  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
8000  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0

[8001 rows x 8 columns]

In [50]:
num_cols_data=X[num_cols]

In [58]:
cat_cols_data[['hitpoint','previous.hitpoint']].astype('object')

hitpoint previous.hitpoint
0           B                 F
1           B                 B
2           B                 F
3           F                 B
4           B                 F
...       ...               ...
7996        F                 F
7997        B                 F
7998        F                 B
7999        F                 B
8000        F                 B

[8001 rows x 2 columns]

In [59]:
cat_cols_data=X[cat_cols]

In [60]:
si=SimpleImputer(missing_values=np.nan,strategy='most_frequent')


In [61]:
si.fit_transform(cat_cols_data)

ValueError: Cannot use most_frequent strategy with non-numeric data:
could not convert string to float: 'B'