In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier

#from xgboost import XGBClassifier

#from vecstack import stacking

from sklearn.model_selection import GridSearchCV

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [9]:
df=pd.read_csv('creditcard.csv',na_values=['?','#','nan'])

In [10]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [11]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [12]:
492/(284315+492)

0.001727485630620034

In [13]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [14]:
X=df.drop('Class', axis=1)

In [15]:
y=df['Class']

In [16]:
X_train, X_test, y_train, y_test =  train_test_split(X,y,test_size=0.3,random_state=0)

In [51]:
randomforest=RandomForestClassifier()

In [38]:
randomforest.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced_subsample')

In [39]:
y_pred=randomforest.predict(X_test)

In [40]:
def evaluate_model(act, pred):
    from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
    print("Confusion Matrix \n", confusion_matrix(act, pred))
    print("Accurcay : ", accuracy_score(act, pred))
    print("Recall   : ", recall_score(act, pred, average='weighted'))
    print("Precision: ", precision_score(act, pred, average='weighted'))  

In [41]:
print("--Train--")
#evaluate_model(y_train, train_pred_RFPipe)
print("--Test--")
evaluate_model(y_test, y_pred)

--Train--
--Test--
Confusion Matrix 
 [[85292     4]
 [   36   111]]
Accurcay :  0.9995318516437859
Recall   :  0.9995318516437859
Precision:  0.999518982916863


In [31]:
y_test.value_counts()

0    85296
1      147
Name: Class, dtype: int64

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.97      0.76      0.85       147

    accuracy                           1.00     85443
   macro avg       0.98      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [48]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)

In [47]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [49]:
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

In [50]:
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0)))

After OverSampling, the shape of train_X: (398038, 30)
After OverSampling, the shape of train_y: (398038,) 

After OverSampling, counts of label '1': 199019
After OverSampling, counts of label '0': 199019


In [52]:
randomforest.fit(X_train_res, y_train_res)

RandomForestClassifier()

In [53]:
y_pred1=randomforest.predict(X_test)

In [54]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.89      0.82      0.85       147

    accuracy                           1.00     85443
   macro avg       0.94      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443



In [55]:
evaluate_model(y_test, y_pred1)

Confusion Matrix 
 [[85281    15]
 [   27   120]]
Accurcay :  0.9995084442259752
Recall   :  0.9995084442259752
Precision:  0.9994928837314843


In [56]:
from imblearn.under_sampling import NearMiss

In [57]:
nr = NearMiss()

In [58]:
X_train_miss, y_train_miss = nr.fit_resample(X_train, y_train.ravel())

In [60]:
print('After UnderSampling, the shape of train_X: {}'.format(X_train_miss.shape))
print('After UnderSampling, the shape of train_y: {} \n'.format(y_train_miss.shape))
  
print("After UnderSampling, counts of label '1': {}".format(sum(y_train_miss == 1)))
print("After UnderSampling, counts of label '0': {}".format(sum(y_train_miss == 0)))

After UnderSampling, the shape of train_X: (690, 30)
After UnderSampling, the shape of train_y: (690,) 

After UnderSampling, counts of label '1': 345
After UnderSampling, counts of label '0': 345


In [61]:
randomforest.fit(X_train_miss, y_train_miss)

RandomForestClassifier()

In [62]:
y_pred2=randomforest.predict(X_test)

In [63]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       1.00      0.70      0.82     85296
           1       0.01      0.95      0.01       147

    accuracy                           0.70     85443
   macro avg       0.50      0.82      0.42     85443
weighted avg       1.00      0.70      0.82     85443



In [64]:
evaluate_model(y_test, y_pred2)

Confusion Matrix 
 [[59518 25778]
 [    8   139]]
Accurcay :  0.6982081621665905
Recall   :  0.6982081621665905
Precision:  0.9981546181768782
