In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier

#from xgboost import XGBClassifier

#from vecstack import stacking

from sklearn.model_selection import GridSearchCV

In [3]:
df=pd.read_csv("03_Movie_Classification.csv")

In [4]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [5]:
df.shape

(506, 19)

In [6]:
df.dtypes

Marketing expense      float64
Production expense     float64
Multiplex coverage     float64
Budget                 float64
Movie_length           float64
Lead_ Actor_Rating     float64
Lead_Actress_rating    float64
Director_rating        float64
Producer_rating        float64
Critic_rating          float64
Trailer_views            int64
3D_available            object
Time_taken             float64
Twitter_hastags        float64
Genre                   object
Avg_age_actors           int64
Num_multiplex            int64
Collection               int64
Start_Tech_Oscar         int64
dtype: object

In [7]:
df.isnull().sum()

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

In [8]:
df.describe()

Marketing expense  Production expense  Multiplex coverage  \
count         506.000000          506.000000          506.000000   
mean           92.270471           77.273557            0.445305   
std           172.030902           13.720706            0.115878   
min            20.126400           55.920000            0.129000   
25%            21.640900           65.380000            0.376000   
50%            25.130200           74.380000            0.462000   
75%            93.541650           91.200000            0.551000   
max          1799.524000          110.480000            0.615000   

             Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
count    506.000000    506.000000          506.000000           506.000000   
mean   34911.144022    142.074901            8.014002             8.185613   
std     3903.038232     28.148861            1.054266             1.054290   
min    19781.355000     76.400000            3.840000             4.035000   
25%    32693.952500    118.525000            7.316250             7.503750   
50%    34488.217500    151.000000            8.307500             8.495000   
75%    36793.542500    167.575000            8.865000             9.030000   
max    48772.900000    173.500000            9.435000             9.540000   

       Director_rating  Producer_rating  Critic_rating  Trailer_views  \
count       506.000000       506.000000     506.000000     506.000000   
mean          8.019664         8.190514       7.810870  449860.715415   
std           1.059899         1.049601       0.659699   68917.763145   
min           3.840000         4.030000       6.600000  212912.000000   
25%           7.296250         7.507500       7.200000  409128.000000   
50%           8.312500         8.465000       7.960000  462460.000000   
75%           8.883750         9.030000       8.260000  500247.500000   
max           9.425000         9.635000       9.400000  567784.000000   

       Time_taken  Twitter_hastags  Avg_age_actors  Num_multiplex  \
count  494.000000       506.000000      506.000000     506.000000   
mean   157.391498       260.832095       39.181818     545.043478   
std     31.295161       104.779133       12.513697     106.332889   
min      0.000000       201.152000        3.000000     333.000000   
25%    132.300000       223.796000       28.000000     465.000000   
50%    160.000000       254.400000       39.000000     535.500000   
75%    181.890000       283.416000       50.000000     614.750000   
max    217.520000      2022.400000       60.000000     868.000000   

          Collection  Start_Tech_Oscar  
count     506.000000        506.000000  
mean    45057.707510          0.545455  
std     18364.351764          0.498422  
min     10000.000000          0.000000  
25%     34050.000000          0.000000  
50%     42400.000000          1.000000  
75%     50000.000000          1.000000  
max    100000.000000          1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [10]:
df.nunique()

Marketing expense      504
Production expense      76
Multiplex coverage      81
Budget                 446
Movie_length           356
Lead_ Actor_Rating     339
Lead_Actress_rating    354
Director_rating        339
Producer_rating        353
Critic_rating           74
Trailer_views          504
3D_available             2
Time_taken             449
Twitter_hastags        423
Genre                    4
Avg_age_actors          42
Num_multiplex          293
Collection             228
Start_Tech_Oscar         2
dtype: int64

In [11]:
df.columns

Index(['Marketing expense', 'Production expense', 'Multiplex coverage',
       'Budget', 'Movie_length', 'Lead_ Actor_Rating', 'Lead_Actress_rating',
       'Director_rating', 'Producer_rating', 'Critic_rating', 'Trailer_views',
       '3D_available', 'Time_taken', 'Twitter_hastags', 'Genre',
       'Avg_age_actors', 'Num_multiplex', 'Collection', 'Start_Tech_Oscar'],
      dtype='object')

In [12]:
y=df['Start_Tech_Oscar']
X=df.drop(['Start_Tech_Oscar'],axis=1)

In [13]:
X.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [14]:
y.head(15)

0     1
1     0
2     1
3     1
4     1
5     0
6     0
7     0
8     1
9     1
10    0
11    0
12    0
13    1
14    1
Name: Start_Tech_Oscar, dtype: int64

In [15]:
y.value_counts()

1    276
0    230
Name: Start_Tech_Oscar, dtype: int64

In [16]:
df.nunique()

Marketing expense      504
Production expense      76
Multiplex coverage      81
Budget                 446
Movie_length           356
Lead_ Actor_Rating     339
Lead_Actress_rating    354
Director_rating        339
Producer_rating        353
Critic_rating           74
Trailer_views          504
3D_available             2
Time_taken             449
Twitter_hastags        423
Genre                    4
Avg_age_actors          42
Num_multiplex          293
Collection             228
Start_Tech_Oscar         2
dtype: int64

In [17]:
num_cols = X.drop(['Genre','3D_available'],axis=1)
cat_cols= X[['Genre','3D_available']]

In [18]:
num_cols=num_cols.columns

In [19]:
cat_cols=cat_cols.columns

In [20]:
X[cat_cols] = X[cat_cols].astype('category')

In [21]:
y=y.astype('category')

In [22]:
X_train, X_test, y_train, y_test =  train_test_split(X,y,test_size=0.3,random_state=0)

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [24]:
numeric_transformer = Pipeline(steps=[('missing_value',SimpleImputer(strategy='mean')),
                     ('scalar1',StandardScaler())])

In [25]:
categorical_transformer = Pipeline(steps=[('missing_value1',SimpleImputer(strategy='most_frequent')),
                                     ('onehotencode',OneHotEncoder(handle_unknown='ignore') )])

In [26]:
preprocessor=ColumnTransformer(transformers=[('num',numeric_transformer, num_cols),('cat',categorical_transformer,cat_cols)])

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
RF_pipe = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier())])

In [35]:
RF_pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('missing_value',
                                                                   SimpleImputer()),
                                                                  ('scalar1',
                                                                   StandardScaler())]),
                                                  Index(['Marketing expense', 'Production expense', 'Multiplex coverage',
       'Budget', 'Movie_length', 'Lead_ Actor_Rating', 'Lead_Actress_rating',
       'Director_rating', 'Producer_rating', 'Critic_rating', 'Trailer_views',
       'Time_taken', 'Twitter_hastags', 'Avg_age_actors', 'Num_multiplex',
       'Collection'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('missing_value1',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencode',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Genre', '3D_available'], dtype='object'))])),
                ('classifier', RandomForestClassifier())])

In [36]:
train_pred_RFPipe = RF_pipe.predict(X_train)
test_pred_RFPipe = RF_pipe.predict(X_test)

In [37]:
def evaluate_model(act, pred):
    from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
    print("Confusion Matrix \n", confusion_matrix(act, pred))
    print("Accurcay : ", accuracy_score(act, pred))
    print("Recall   : ", recall_score(act, pred, average='weighted'))
    print("Precision: ", precision_score(act, pred, average='weighted'))  

In [38]:
print("--Train--")
evaluate_model(y_train, train_pred_RFPipe)
print("--Test--")
evaluate_model(y_test, test_pred_RFPipe)

--Train--
Confusion Matrix 
 [[167   0]
 [  0 187]]
Accurcay :  1.0
Recall   :  1.0
Precision:  1.0
--Test--
Confusion Matrix 
 [[38 25]
 [32 57]]
Accurcay :  0.625
Recall   :  0.625
Precision:  0.6320121951219512


In [39]:
from sklearn.ensemble import AdaBoostClassifier

In [40]:
Ada_boost_pipe = Pipeline(steps=[('preprocessor1', preprocessor),
                      ('classifier2', AdaBoostClassifier())])

In [41]:
Ada_boost_pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocessor1',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('missing_value',
                                                                   SimpleImputer()),
                                                                  ('scalar1',
                                                                   StandardScaler())]),
                                                  Index(['Marketing expense', 'Production expense', 'Multiplex coverage',
       'Budget', 'Movie_length', 'Lead_ Actor_Rating', 'Lead_Actress_rating',
       'Director_rating', 'Producer_rating', 'Critic_rating', 'Trailer_views',
       'Time_taken', 'Twitter_hastags', 'Avg_age_actors', 'Num_multiplex',
       'Collection'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('missing_value1',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencode',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Genre', '3D_available'], dtype='object'))])),
                ('classifier2', AdaBoostClassifier())])

In [42]:
train_pred_ada = Ada_boost_pipe.predict(X_train)
test_pred_ada = Ada_boost_pipe.predict(X_test)

In [43]:
print("--Train--")
evaluate_model(y_train, train_pred_ada)
print("--Test--")
evaluate_model(y_test, test_pred_ada)

--Train--
Confusion Matrix 
 [[138  29]
 [ 25 162]]
Accurcay :  0.847457627118644
Recall   :  0.847457627118644
Precision:  0.8474402059616287
--Test--
Confusion Matrix 
 [[37 26]
 [42 47]]
Accurcay :  0.5526315789473685
Recall   :  0.5526315789473685
Precision:  0.5711032827430115
